[package]
name = "serde_bencode"
version = "0.1.0"
authors = ["Caleb Webber <caleb.webber@unos.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.118"